### ISSUE TITLE
Ticking World Crash When Loading A World or Creating A New World [1.16.4/5]

### ISSUE THREAD

**Issue by Coraline77447** [UltimateBoomer/smoothboot-fabric#10]
Hi, I'm experiencing a ticking world crash that's coming from Smooth Boot and another mod called Abnormals Core with the mixin that they use. Here's the crash report and log;

Crash Report:  [crash-2021-01-16_05.58.44-server.txt](https://github.com/UltimateBoomer/mc-smoothboot/files/5824350/crash-2021-01-16_05.58.44-server.txt)

Log:  [latest.log](https://github.com/UltimateBoomer/mc-smoothboot/files/5824351/latest.log)

NOTE: Even tho I didn't see or couldn't see Smooth Boot in the Blame logs in my logs folder but in the crash report I did find Smooth Boot in there that its mixin along with Abnormals Core's mixin caused my new modded world to die without me ever spawning into the world...

UPDATE: I tried to create another world and it died again but without the mods i've though caused this and found out that OptiFine may be the one that's causing this since there's no 1.16.5 version for OptiFine yet. Im going to take out optifine and see if I can make a new world. 

UPDATE 2: I tried to make another test world and it too died by the same ticking world crash but without smoothboot, abnormals-core, and optifine... I truly don't know what's causing this.... I seriously need help finding out which mod or mods that I have that are causing this mess...... I think that this issue relates to forge not the mods... The forge devs did somethin with the mixin and now I can't create a new world or load into an existing one since I get the java.lang.NoSuchMethodError....

**Comment by UltimateBoomer** [comment]
Does it work on 1.16.4? 1.16.5 is still new and may have brought changes that breaks some mods even if it is network compatible with 1.16.4.

**Comment by Coraline77447** [comment]
Yea, I've noticed that smooth boot for 1.16.4 doesn't work for 1.16.5. So I'm sorry for makin this useless report and wasting your time on it...
So I'm sorta glad that you closed my useless report😔....
